export const USER_ROLE = {
  MANAGER: "MANAGER",
  TEAM_MEMBER: "TEAM_MEMBER",
  DEVELOPER: "DEVELOPER",
  DESIGNER: "DESIGNER",
  TESTER: "TESTER",
  SUPPORT_ENGINEER: "SUPPORT_ENGINEER",
  BUSINESS_ANALYST: "BUSINESS_ANALYST",
  PROJECT_MANAGER: "PROJECT_MANAGER",
  ADMIN: "ADMIN"
} as const;

export type UserRole = (typeof USER_ROLE)[keyof typeof USER_ROLE];

export const MEMBERSHIP_ROLE = {
  OWNER: "OWNER",
  MANAGER: "MANAGER",
  CONTRIBUTOR: "CONTRIBUTOR",
  VIEWER: "VIEWER"
} as const;

export type MembershipRole = (typeof MEMBERSHIP_ROLE)[keyof typeof MEMBERSHIP_ROLE];

export const PROJECT_STATUS = {
  PLANNING: "PLANNING",
  ACTIVE: "ACTIVE",
  ON_HOLD: "ON_HOLD",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED"
} as const;

export type ProjectStatus = (typeof PROJECT_STATUS)[keyof typeof PROJECT_STATUS];

export const TASK_STATUS = {
  TODO: "TODO",
  IN_PROGRESS: "IN_PROGRESS",
  REVIEW: "REVIEW",
  DONE: "DONE"
} as const;

export type TaskStatus = (typeof TASK_STATUS)[keyof typeof TASK_STATUS];

export const TASK_PRIORITY = {
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
  URGENT: "URGENT"
} as const;

export type TaskPriority = (typeof TASK_PRIORITY)[keyof typeof TASK_PRIORITY];

export const ACTIVITY_ACTION = {
  USER_REGISTERED: "USER_REGISTERED",
  USER_LOGGED_IN: "USER_LOGGED_IN",
  PROJECT_CREATED: "PROJECT_CREATED",
  PROJECT_UPDATED: "PROJECT_UPDATED",
  PROJECT_ARCHIVED: "PROJECT_ARCHIVED",
  PROJECT_MEMBER_ADDED: "PROJECT_MEMBER_ADDED",
  PROJECT_MEMBER_REMOVED: "PROJECT_MEMBER_REMOVED",
  TASK_CREATED: "TASK_CREATED",
  TASK_UPDATED: "TASK_UPDATED",
  TASK_DELETED: "TASK_DELETED",
  TASK_STATUS_CHANGED: "TASK_STATUS_CHANGED",
  TASK_ASSIGNED: "TASK_ASSIGNED",
  COMMENT_ADDED: "COMMENT_ADDED",
  TEAM_MEMBER_INVITED: "TEAM_MEMBER_INVITED",
  TEAM_MEMBER_REMOVED: "TEAM_MEMBER_REMOVED",
  PROFILE_UPDATED: "PROFILE_UPDATED"
} as const;

export type ActivityAction = (typeof ACTIVITY_ACTION)[keyof typeof ACTIVITY_ACTION];
